namespace:
  name: prod

deployment:
  replicaCount: 2
  image:
    name: nginx
    tag: 1.17.0
  template:
    resources:
      cpu: 70m
      memory: 256Mi

service:
  port: 80

configMap:
  data:
    version: 1.17.0

