apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: demo2
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP
status:
  loadBalancer: {}
